#!/bin/bash

#/*
#* git2git_file push one file with commit history from one git to another one
#* Copyright (C) 2024 Antoine DELAPORTE
#*
#* This program is free software: you can redistribute it and/or modify
#* it under the terms of the GNU General Public License as published by
#* the Free Software Foundation, either version 3 of the License, or
#* (at your option) any later version.
#*
#* This program is distributed in the hope that it will be useful,
#* but WITHOUT ANY WARRANTY; without even the implied warranty of
#* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#* GNU General Public License for more details.
#*
#* You should have received a copy of the GNU General Public License
#* along with this program.  If not, see <http://www.gnu.org/licenses/>.
#*/

if [ $# != 4 ]; then
    cat <<EOF
Script qui permet de transferer un fichier d\'un git a un autre avec un commentaire

Les parametres doivent etres mis dans l\'ordre qui suis
    Repo Source
    Fichier Source avec son path dans le git
    Repo Destination
    Fichier Destination avec son path dans le git
EOF
    exit 0
fi

RepoSrc=$1
FileSrc=$2

RepoDst=$3
FileDst=$4



gitoune -r ${RepoSrc} -f ${FileSrc} -l | grep --color=never "^\*" | sed -e "s=^\* '==g" -e "s=^\(.*\) (2...-.*$=\1=g" -e "s= - = =g" | tac | while read id msg
    do
        gitoune -r ${RepoSrc} -f ${FileSrc} -G $id | gitoune -r ${RepoDst} -f ${FileDst} -m "${msg}"
        done
