version: '3'
services:
    postfix:
        build:
            context: src
            dockerfile: Dockerfile-pf
        image: local/postfix
        restart: unless-stopped
        hostname: pf-mua.example.com
        container_name: pf-mua.example.com
        ports:
            - 172.17.0.1:2535:25
        volumes:
            - /home/_Dockers/mua.example.com/POC/etc+postfix:/etc/postfix
            - /home/_Dockers/mua.example.com/POC/var+spool+postfix:/var/spool/postfix
#        command: sleep infinity
#        depends_on:
#            - mua
