#!/usr/bin/perl

use strict;
use warnings;

use Getopt::Std;

my %ansiColor=( 'Red'=>31, 'Green'=>32, 'Yellow'=>33, 'Blue'=>34, 'Magenta'=>35, 'Cyan'=>36, 'White'=>37, 'Gray'=>90 );

sub printColor {
    my ($color,$truc2prn)=@_;
    print("\e[$ansiColor{$color}m".$truc2prn."\e[0m");
    }

sub print_usage {
    print("-t le channel-id sur le quel on sort les morceaux du dialplan correspondant, NEEDED\n");
    print("-f le fichuier de log, par defaut /var/log/asterisk/full, permet de faire zcat XXXX | truc -f -\n");
    print("-a l,c,i Affiche les logs,la conf correspondante et les interlogues (defaut l,c,i\n");
    print("-n exten1\@context,exten2\@context n'affiche pas les extension precises\n");
    print('-m chaine    permet de faire rougir les lignes contenant chaine dans l');
    exit(1);
    }


sub astloadcontext {
    my ($excont)=@_;
    my @ret;
    open(AST,'-|','rasterisk -rx "dialplan show '.$excont.'"');
    push(@ret,$excont);
    while(<AST>) {
        chomp();
        s/.*(\d)\. (.*)\[.*\]/$1 $2/g; #Espaces finaux conserves, desole
        s/\s+$//;
        if(/^\d/) {
            my($linu,$cha)=split(/ /,$_,2);
            push(@ret,$cha);
            }
        }
    return(@ret);
    }

my %opts;
getopts("t:f:a:n:m:",\%opts) or print_usage();


my @logType=['l','c','i'];
my @noDispExten=[''];
my $log="/var/log/asterisk/full";
my $matchLog='';
if(!defined($opts{'t'}))    { print_usage(); }
if(defined($opts{'f'}))     { $log=$opts{'f'}; }
if(defined($opts{'a'}))     { @logType=split(/,/,$opts{'a'}); }
if(defined($opts{'n'}))     { @noDispExten=split(/,/,$opts{'n'}); }
if(defined($opts{'m'}))     { $matchLog=$opts{'m'}; }


my @mrks=split(/,/,$opts{'t'});
my %tacont;

my $FL=*STDIN;
if($log ne "-")     { open($FL,'<',$log) or die $! };

my $curli="";
my $coloChoosed;

while(my $line=<$FL>) {
    foreach my $mrk (@mrks) {
        $_=$line;
        if(/\]\[$mrk\]/) {
            chomp();
            if(/\]\[$mrk\] pbx.c: Executing \[/) {
                $curli=$_;
                # [Oct 18 09:01:52] VERBOSE[275996][C-000002ac] pbx.c: Executing [33164764275@from-external:1] NoOp("IAX2/TOOTAi-2924", "[C-000002ac] Icelus Clay 33164764275 Appel entrant de 0618497867 0618497867") in new stack
                s/^.* pbx.c: Executing \[(.*)@(.*):(\d*)\] .*/$1\@$2 $3/;
                my($excont,$linnuco)=split(/ /);
                if(!defined($tacont{$excont})) { 
                    $tacont{$excont}=[];
                    $tacont{$excont}=[astloadcontext($excont)];
                }
                if (not ($excont ~~ @noDispExten)) {
                    if('l' ~~ @logType) {
                        $coloChoosed='White';
                        if(length($matchLog) and $curli =~ /$matchLog/) { $coloChoosed='Red'; }
                        printColor($coloChoosed,$curli."\n");
                        }
                    if(defined($tacont{$excont}[int($linnuco)]) and 'c' ~~ @logType) {
                        printColor('Blue',"        [$excont:$linnuco]:");
                        printColor("Yellow",$tacont{$excont}[int($linnuco)]."\n");
                        }
                    # else { print("=======$excont/".int($linnuco)."\n"); }
                    }
                }
            elsif('i' ~~ @logType) {
                printColor('Gray',$_."\n");
                }
            }
        }
    }

if($log ne "-")     { close($FL); }