#!/usr/bin/perl

use strict;
use warnings;

use Getopt::Std;
use IO::Uncompress::Gunzip;

my %ansiColor=( 'Red'=>31, 'Green'=>32, 'Yellow'=>33, 'Blue'=>34, 'Magenta'=>35, 'Cyan'=>36, 'White'=>37, 'Gray'=>90 );
my $nocolor=0;

sub printColor {
    my ($color,$truc2prn)=@_;
    if($nocolor) {
        print($truc2prn);
        }
    else {
        print("\e[$ansiColor{$color}m".$truc2prn."\e[0m");
        }
    }

sub print_usage {
    print("-t le channel-id sur le quel on sort les morceaux du dialplan correspondant, NEEDED\n");
    print("-f le fichuier de log, par defaut /var/log/asterisk/full mais stdin autorise  zcat XXXX | truc\n");
    print("-a l,c,i Affiche les logs,la conf correspondante et les interlogues (defaut l,c,i)\n");
    print("-n exten1\@context,exten2\@context n'affiche pas les extension precises\n");
    print("-w white, no color\n");
    print('-m chaine    permet de faire rougir les lignes contenant chaine dans les logs');
    print("Si des données sont presente sur le stdin, cela by passe le -f\n");
    exit(1);
    }

sub astloadcontext {
    my ($excont)=@_;
    my @ret;
    open(AST,'-|','rasterisk -rx "dialplan show '.$excont.'"');
    push(@ret,$excont);
    while(<AST>) {
        chomp();
        s/.*(\d)\. (.*)\[.*\]/$1 $2/g; #Espaces finaux conserves, desole
        s/\s+$//;
        if(/^\d/) {
            my($linu,$cha)=split(/ /,$_,2);
            push(@ret,$cha);
            }
        }
    return(@ret);
    }


my %opts;
getopts("t:f:a:n:m:w",\%opts) or print_usage();

my @logType=['l','c','i'];
my @noDispExten=[''];
my $log="/var/log/asterisk/full";
my $matchLog='';
if(!defined($opts{'t'}))    { print_usage(); }
if(defined($opts{'f'}))     { $log=$opts{'f'}; }
if(defined($opts{'a'}))     { @logType=split(/,/,$opts{'a'}); }
if(defined($opts{'n'}))     { @noDispExten=split(/,/,$opts{'n'}); }
if(defined($opts{'m'}))     { $matchLog=$opts{'m'}; }
if(defined($opts{'w'}))     { $nocolor=1; }


my @mrks=split(/,/,$opts{'t'});
my %tacont;

my $FD=*STDIN;
my $rastdin=-t STDIN;
if($rastdin and $log eq "-") { print "Bug dans la matrice ya rien dans le stdin";die $! }
elsif($rastdin)             { open($FD,'<',$log) or die $! };

my $curli="";
my $coloChoosed;

my $DESC = IO::Uncompress::Gunzip->new($FD)
    or die "Erreur de décompression: $IO::Uncompress::Gunzip::GunzipError\n";

while (my $line = <$DESC>) {
    foreach my $mrk (@mrks) {
        $_=$line;
        if(/\]\[$mrk\]/) {
            chomp();
            if(/\]\[$mrk\] pbx.c: Executing \[/) {
                $curli=$_;
                # [Oct 18 09:01:52] VERBOSE[275996][C-000002ac] pbx.c: Executing [33164764275@from-external:1] NoOp("IAX2/TOOTAi-2924", "[C-000002ac] Icelus Clay 33164764275 Appel entrant de 0618497867 0618497867") in new stack
                s/^.* pbx.c: Executing \[(.*)@(.*):(\d*)\] .*/$1\@$2 $3/;
                my($excont,$linnuco)=split(/ /);
                if(!defined($tacont{$excont})) { 
                    $tacont{$excont}=[];
                    $tacont{$excont}=[astloadcontext($excont)];
                }
                if (not ($excont ~~ @noDispExten)) {
                    if('l' ~~ @logType) {
                        $coloChoosed='White';
                        if(length($matchLog) and $curli =~ /$matchLog/) { $coloChoosed='Red'; }
                        printColor($coloChoosed,$curli."\n");
                        }
                    if(defined($tacont{$excont}[int($linnuco)]) and 'c' ~~ @logType) {
                        printColor('Blue',"        [$excont:$linnuco]:");
                        printColor("Yellow",$tacont{$excont}[int($linnuco)]."\n");
                        }
                    # else { print("=======$excont/".int($linnuco)."\n"); }
                    }
                }
            elsif('i' ~~ @logType) {
                printColor('Gray',$_."\n");
                }
            }
        }
    }

#close($FD) if $FD != \*STDIN;  # Ne pas fermer STDIN si on l'utilise
if($log ne "-")     { close($FD); }
close($DESC) if $DESC;  # Fermer le FDux de décompression si nécessaire