#!/usr/bin/env python3

#/*
#* cronMutt send mail or not, push on nextcloud, etc the return of an command
#* Copyright (C) 2024 Antoine DELAPORTE
#*
#* This program is free software: you can redistribute it and/or modify
#* it under the terms of the GNU General Public License as published by
#* the Free Software Foundation, either version 3 of the License, or
#* (at your option) any later version.
#*
#* This program is distributed in the hope that it will be useful,
#* but WITHOUT ANY WARRANTY; without even the implied warranty of
#* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#* GNU General Public License for more details.
#*
#* You should have received a copy of the GNU General Public License
#* along with this program.  If not, see <http://www.gnu.org/licenses/>.
#*/



# Le programme ne doit rien faire si son stdin est vide (-S alors il petera quand emem son mail)
# Le programme doit gerener le in reply to si necessaire (-i blah)
# Le programme doit generer le sujet si necessaire (-s subject)
# Le programme doit envoyer a l'user executant  (-d email) LOGNAME
# on peut programmer le a qui con repond et le message id  ( -r / -m )
# ca peut etre lui le lanceur il n'est pas que piped Et ainsi on peut recuperer le stderr (-e '')

### Pour les version python anterieur a 3.6
### pip install future-fstrings
### -*- coding: future_fstrings -*-

import getopt,sys
import io
import re
import os
import hashlib
import subprocess
import threading
import tempfile
import shutil
from urllib.parse import urlsplit,unquote
import uuid
from datetime import datetime
import requests
from requests.auth import HTTPBasicAuth

Version="0.24.1"
### Todo intercepter le keyboard interrupt
### Todo ajouter l'usage d'un fichier de donc mode@fichier => muodule mode du fichier fichier
# 0.24.1 noms de variables et de fonctions explicites, sans changement de comportement
# 0.24 nextcloud en echec (injoignable, timeout, erreur HTTP, -n/-N incomplet) : mail a tous (-d et -o),
#      sujet "**Output non sauvé**", l'output en piece jointe sous le nom prevu sur le nextcloud
# 0.23 en-tete References (meme valeur que In-Reply-To), utilise en premier par Thunderbird et Gmail pour les fils
# 0.22 In-Reply-To au format RFC <id@cronMutt> (sans l'hote : le fil reste commun a toutes les machines)
# 0.21 Message-ID unique et conforme RFC par defaut, -m complete en <id@host> ; -n sans -N (ou l'inverse) signale et bascule sur le mail
# 0.20 mode pipe réparé (stdin relu), indentation conservée, échappement des my_hdr pour mutt,
#      nextcloud : mot de passe avec ':', erreurs réseau et timeout, logique d'envoi de la 0.16/0.17.1 restaurée,
#      -o no + nextcloud en échec n'écrit plus à "no", -r pose Reply-To, --help, stdin fermé pour -e,
#      décodage tolérant, code retour 128+signal, échec mutt signalé sur stderr, code mort retiré
# 0.19 license header
# 0.18.3 correction du pb utf8 vue grace au 0.18.2 sur la poussée de donnes vers le nc
# 0.18.2 correction d'une coquille pour les stderr par mail
# 0.18.1 deplacement de l'initialisation de var afin d'eviter les bug
# 0.18 correctif si on n'a pas d'environnement
# 0.17.4 Rajout de points de debug
# 0.17.3 si -o no alors on n'envoie pas de mail lorsque tout va bien (meme s'il y a du monde)
# 0.17.2 debug sur les emissions empty ou pas, etc
# 0.17.1 L'option -o force maintenant le mail malgres le nextcloud
# 0.17 On rajoute un flag -o qui envoie systematiquement le mail lorsque c'est ok (a ceux preciser dans le -o
# 0.16 Si tout va bien on pousse sur le nc. Si le -E on envoie le gentil mail quand meme. Si tout vat mal, nc+mail
# 0.15.1 Saut de ligne manquant, corrige
# 0.15 L'affichage stdout se fait en direct, on n'attends plus que le process soit execute
# 0.14 On renvoie le meme errorcode que le programme execute en fin sys.ext
# 0.13 On rajoute le hostname dans les entees
# 0.12 On tete de faire de l'autodetection pour le teemode
# 0.11 On gere les pb de caracteres space de microsoft
# 0.10 Pipe mode fonctionnelle : on flush
# 0.9 New header : date debut execution/ commande lancee / exit code
# 0.8.1 On rajoute un header propre a cet outils sans la faute
# 0.7 On rajoute une notion de priorite
# 0.6 On jolieffie le from
# 0.5 en mode tee, on ne saute pas de lignes
# 0.4 Activation du X (no sub chg), Ajout du changement du from, Ajout du tee mode (dump en meme temps que mail le stdout et stderr)
# 0.3 Rajout du traitement des erreures
# 0.2 On rajoute le versionning a cronMutt
# 0.1  Un outils pour mieux gerer l'envoie des mails a partir des corns

def nextcloudUpload(webdavUrl,credentials,output):
    # Prepare auth (le mot de passe peut contenir des ':')
    loginPassword=credentials.split(':',1)
    auth = HTTPBasicAuth(loginPassword[0],loginPassword[1] if len(loginPassword) > 1 else '')
    # Envoyer le fichier au partage Nextcloud
    # Renvoie None si le depot a reussi, sinon la raison de l'echec
    try:
        # 15 s pour se connecter, 120 s sans reponse
        response = requests.put(webdavUrl, data=output, auth=auth, timeout=(15,120))
    except requests.Timeout as err:
        failureReason=f"pas de reponse (timeout) : {err}"
    except requests.RequestException as err:
        failureReason=f"injoignable : {err}"
    else:
        # Vérifier le succès de l'opération
        if response.status_code in [200, 201, 204]:
            return(None)
        failureReason=f"HTTP {response.status_code} {response.reason}"
    print(f"cronMutt: depot nextcloud en echec, {failureReason}",file=sys.stderr)
    return(failureReason)

def nextcloudFileName(webdavUrl):
    # Nom du fichier tel qu'il aurait du etre depose sur le nextcloud
    name=None
    if webdavUrl is not None:
        name=os.path.basename(unquote(urlsplit(webdavUrl).path).rstrip('/'))
    return(name if name else "cronMutt-output.txt")

def sendMail(muttCommand,body):
    muttProcess=subprocess.Popen(muttCommand,encoding ='utf-8',
                         stdin=subprocess.PIPE,
                         stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE)
    _,muttStderr=muttProcess.communicate(input=body)
    if muttProcess.returncode != 0:
        print(f"cronMutt: mutt a echoue (exit={muttProcess.returncode}) : {muttStderr.strip()}",file=sys.stderr)
    return(muttProcess.returncode)

def escapeMuttValue(value):
    # mutt interprete la valeur d'un my_hdr : ; et # la coupent, ` execute, $ expanse
    value=value.replace('\r',' ').replace('\n',' ')
    return(re.sub(r'([\\;#`$])',r'\\\1',value))


def printVersion():
    print(f"Version {Version}")
    sys.exit(0)

def printUsage():
    print("     E       Mail even empty data")
    print("     i:      in-reply-to")
    print("     s:      Mail subject")
    print("     d:      Destination email")
    print("     o:      Destinataire ok mail (sinon c'est uniquement pour les d)")
    print("     r:      ReplyTo")
    print("     f:      from (si different du reply to)")
    print("     m:      message id (defaut: unique a chaque mail)")
    print("     e:      excute command")
    print("     c       cache la commande du header")
    print("     t:      type du mail")
    print("     X       fonctionelle avec le mode -e xxxx, ne change pas le sujet sur exit code")
    print("     p:      code Page encoding (default: utf8 / ISO-8859–16)")
    print("     T       mode tee affiche a l'ecran")
    print("     n:      url path avec nom de fichier webdav du nextcloud")
    print("     N:      login:password du nextcloud")
    print("     D       debug")
    print("     h       Helpeur")
    print("     V       Version")
    sys.exit(123)

def readStream(stream, capturedLines, streamName):
    for line in stream:
        capturedLines[streamName].append(line.rstrip())
        if teeMode:
            if streamName == 'stderr':
                print("[STDERR]:",end='',flush=True)
            print(line,end="",flush=True)
    stream.close()

try:
    options, _ = getopt.getopt(sys.argv[1:], "hVDEi:s:d:o:r:f:m:e:ct:XTp:n:N:", ["help"])
except getopt.GetoptError as err:
    print(err)  # will print something like "option -a not recognized"
    printUsage()

debug=False
sendEvenIfEmpty=False
mailSubject=f"//cron//{os.path.basename(__file__)}"
inReplyTo=None
recipients=os.getenv('LOGNAME','nobody')
recipientsIfOk=None
messageId=None
command=None
mailContentType=None
replyTo=os.getenv("LOGNAME",'nobody')
replyToGiven=False
markSubjectOnError=True
if sys.stdin.isatty():
    teeMode=True
else:
    teeMode=False
mailFrom=None
#-e "set content_type=text/html" 
hideCommandHeader=False
outputEncoding="utf-8"
nextcloudUrl=None
nextcloudCredentials=None

for option,value in options:
    if   option in ('-h','--help'):
        printUsage()
    elif option in '-V':
        printVersion()
    elif option in '-D':
        debug=True
    elif option in '-E':
        sendEvenIfEmpty=True
    elif option in '-i':
        inReplyTo=value
    elif option in '-s':
        mailSubject=value
    elif option in "-d":
        recipients=value
    elif option in '-o':
        recipientsIfOk=value
    elif option in '-f':
        mailFrom=value
    elif option in "-r":
        replyTo=value
        replyToGiven=True
    elif option in "-m":
        messageId=value
    elif option in "-e":
        command=value
    elif option in '-t':
        mailContentType=value
    elif option in '-X':
        markSubjectOnError=False
    elif option in '-T':
        teeMode=True
    elif option in '-c':
        hideCommandHeader=True
    elif option in '-p':
        outputEncoding=value
    elif option in '-n':
        nextcloudUrl=value
    elif option in "-N":
        nextcloudCredentials=value
    

hostname=os.uname()[1]
# Message-ID : unique par defaut (un id fixe fait dedoublonner les mails), toujours au format <id@host>
if messageId is None:
    messageId=f'<{datetime.now().strftime("%Y%m%d%H%M%S")}.{os.getpid()}.{uuid.uuid4().hex[:12]}.cronMutt@{hostname}>'
elif "<" not in messageId:
    messageId=f'<{messageId}>' if "@" in messageId else f'<{messageId}@{hostname}>'
nextcloudEnabled=nextcloudUrl is not None and nextcloudCredentials is not None
nextcloudIncomplete=(nextcloudUrl is None) != (nextcloudCredentials is None)
if nextcloudIncomplete:
    print("cronMutt: -n et -N vont ensemble, pas de depot nextcloud, envoi par mail",file=sys.stderr)

if inReplyTo is None:
    inReplyTo=hashlib.md5(mailSubject.encode('utf-8')).hexdigest()
# In-Reply-To : format <id@droite> sinon les clients l'ignorent pour les fils
if "<" not in inReplyTo:
    inReplyTo=f'<{inReplyTo}>' if "@" in inReplyTo else f'<{inReplyTo}@cronMutt>'
if mailFrom is None:
    mailFrom=replyTo
if "<" not in mailFrom:
    fromAddress=mailFrom
    mailFrom=f'{fromAddress.split("@")[0]} <{fromAddress}>'
    if debug:
        print(f"{fromAddress} ET {mailFrom}")
        print(f'{fromAddress.split("@")}')

# Preparation Ouverture du mail 1/2
muttCommand=['mutt','-e',f'my_hdr X-cronMutt: cronMutt-{Version}','-e',f'my_hdr X-cronMuttStart: {str(datetime.now())}','-e',f'my_hdr X-cronMuttHost: {hostname}','-e',f'my_hdr From:{escapeMuttValue(mailFrom)}','-e',f'my_hdr In-Reply-To: {escapeMuttValue(inReplyTo)}','-e',f'my_hdr References: {escapeMuttValue(inReplyTo)}','-e',f'my_hdr Message-ID: {escapeMuttValue(messageId)}']
if replyToGiven:
    muttCommand.append('-e')
    muttCommand.append(f'my_hdr Reply-To: {escapeMuttValue(replyTo)}')


# Ouverture du process a suivre
commandExitCode=0
capturedOutput={}
capturedOutput['stdout']=[]
capturedOutput['stderr']=[]

if command is not None:
    if not hideCommandHeader:
        muttCommand.append('-e')
        muttCommand.append(f'my_hdr X-cronMuttCmd: {escapeMuttValue(command)}')

    commandProcess=subprocess.Popen(['/bin/sh','-c',command],encoding =outputEncoding,errors='replace',
                         stdin=subprocess.DEVNULL,
                         stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE)

    # Creation puis demarrage des threads de lecture du stdout et stderr
    stdoutReader = threading.Thread(target=readStream, args=(commandProcess.stdout, capturedOutput, "stdout"))
    stderrReader = threading.Thread(target=readStream, args=(commandProcess.stderr, capturedOutput, "stderr"))
    stdoutReader.start()
    stderrReader.start()

    #Attente de la fin d'exec des thread et process (les thread affichent en tps reel)
    stdoutReader.join()
    stderrReader.join()
    commandProcess.wait()

    commandExitCode=commandProcess.returncode

    muttCommand.append('-e')
    muttCommand.append(f'my_hdr X-cronMuttExitCode: {str(commandProcess.returncode)}')

    if markSubjectOnError and commandExitCode != 0:
        mailSubject="*** "+mailSubject
        if debug:
            print(f"exit={commandProcess.returncode}")
else:
    # Mode pipe : les donnees arrivent sur notre stdin
    readStream(io.TextIOWrapper(sys.stdin.buffer,encoding=outputEncoding,errors='replace'), capturedOutput, "stdout")

# Traitement des donnees
output=""
for line in capturedOutput['stdout']:
    output+=line+"\n"
if len(capturedOutput['stderr']):
    output+="\n=============================================================================\n"
    for line in capturedOutput['stderr']:
        output+=line+"\n"

# Depot de la donnee sur le nextcloud
nextcloudFailure=None
if nextcloudIncomplete:
    nextcloudFailure="-n et -N vont ensemble, aucun depot tente"
elif nextcloudEnabled:
    if debug:
        print(f'Depose sur nc {nextcloudUrl}')
    nextcloudFailure=nextcloudUpload(nextcloudUrl,nextcloudCredentials,output.encode('utf-8'))

# Nextcloud en echec : l'output n'est sauve nulle part, tout le monde est prevenu et l'a en piece jointe
nextcloudFailed=nextcloudFailure is not None
mailBody=output
attachmentDir=None
if nextcloudFailed:
    mailSubject="**Output non sauvé** "+mailSubject
    mailBody=f"Output non sauvé, dépôt Nextcloud en échec : {nextcloudFailure}\nIl est en pièce jointe.\n"
    mailBody+="\n=============================================================================\n"+output
    attachmentDir=tempfile.mkdtemp(prefix="cronMutt.")
    attachmentFile=os.path.join(attachmentDir,nextcloudFileName(nextcloudUrl))
    with open(attachmentFile,'w',encoding='utf-8') as attachment:
        attachment.write(output)

# Preparation Ouverture du mail 2/2
muttCommand.append('-s')
muttCommand.append(mailSubject)

if mailContentType is not None:
    muttCommand.append('-e')
    muttCommand.append(f'set content_type=text/{mailContentType}')
if commandExitCode != 0 or nextcloudFailed:
    muttCommand.append('-e')
    muttCommand.append('my_hdr X-Priority:1')
if nextcloudFailed:
    muttCommand.append('-a')
    muttCommand.append(attachmentFile)
muttCommand.append('--')

# Destinataires : -o seul quand tout va bien, sinon -d et -o
if recipientsIfOk is not None and recipientsIfOk != "no" and commandExitCode == 0 and not nextcloudFailed:
    muttCommand.append(recipientsIfOk)
else:
    if recipientsIfOk is not None and recipientsIfOk != "no":
        recipients+=","+recipientsIfOk
    muttCommand.append(recipients)

if debug:
    print(f"{' '.join(muttCommand)}")

# Je veux envoyer le mail si
#   * Le nextcloud n'a pas marché (ou -n/-N incomplet)
#   * il y a une errere
#   * sauf -o no, quand tout va bien
#   * avec nextcloud : il y a un -E ou un -o (l'output est deja sur le nc)
#   * sans nextcloud : il y a un -E ou de l'output

mustSendMail=False
if nextcloudFailed:
    mustSendMail=True
    if debug:
        print('Not Sended')
elif commandExitCode != 0:
    mustSendMail=True
    if debug:
        print(f'ExitCode-{commandExitCode}')
elif recipientsIfOk == "no":
    mustSendMail=False
    if debug:
        print('destok no')
elif nextcloudEnabled:
    mustSendMail=sendEvenIfEmpty or recipientsIfOk is not None
    if debug:
        print(f'nc ok, send={mustSendMail}')
elif sendEvenIfEmpty or len(output):
    mustSendMail=True
    if debug:
        print('Send empty if empty en full if len')
else:
    if debug:
        print('Fall back')
    mustSendMail=False

if mustSendMail:
    sendMail(muttCommand,mailBody)
    if debug:
        print(f"Sended-{len(mailBody)}")
if attachmentDir is not None:
    shutil.rmtree(attachmentDir,ignore_errors=True)

if debug:
    print(len(output))

# Tue par un signal : returncode negatif, on rend 128+signal comme le shell
sys.exit(128-commandExitCode if commandExitCode < 0 else commandExitCode)
