#!/bin/bash


grep ": Accepted publickey for " /var/log/auth.log | tr -s "\t " " " | cut -d" " -f1-4,9,11,13,15,16 | while read d1 d2 d3 d4 login ip port rsa cles
    do
    holo=$(getent passwd $login | cut -d: -f6)
    grep -v "^#" $holo/.ssh/authorized_keys | sed -s "s/.*\(ssh-.*\)/\1/g" | sort -u | ssh-keygen -lf - | while read null clef com
        do
            if [ "$cles" = "$clef" ]; then
                echo $d1 $d2 $d3 $d4: $login $ip:$port $com
            fi
        done
    done