http {
        perl_modules perl/lib;
        perl_require mailauth.pm;
        server {
                listen 127.0.0.1:3615;
                location /auth {
                    perl mailauth::handler;
                    }
                }
        }
