FROM ubuntu:22.04

RUN mkdir /opt/tgz

RUN apt-get update \
    && apt-get install -y --no-install-recommends postfix \
    && rm -rf /var/lib/apt/lists/*


RUN tar czf /opt/tgz/etc+postfix.tgz /etc/postfix
RUN tar czf /opt/tgz/var+spool+postfix.tgz /var/spool/postfix

RUN rm -rf /etc/postfix /var/spool/postfix
RUN mkdir /etc/postfix /var/spool/postfix

RUN echo 'maillog_file = /dev/stdout' >>/etc/postfix/main.cf

RUN echo '#!/bin/bash\n\
cd /\n\
test -e /etc/postfix/master.cf  || echo Uncompressing etc\n\
test -e /etc/postfix/master.cf  ||  tar xzf /opt/tgz/etc+postfix.tgz\n\
test -e /var/spool/postfix/private/smtp || echo Uncompressing varspool\n\
test -e /var/spool/postfix/private/smtp ||  tar xzf /opt/tgz/var+spool+postfix.tgz\n\
test -e /etc/mailname || echo Creating /etc/mailname\n\
test -e /etc/mailname || /usr/bin/hostname >/etc/mailname\n\
echo Compiling\n\
/usr/bin/newaliases\n\
echo Running\n\
/usr/sbin/postfix start-fg\n\
\n\
' >/run.sh

RUN chmod +x /run.sh

CMD [ "/run.sh" ]
