services:
  nginx:
    container_name: nginx
    hostname: nginx
    #image: nginx:1.19
    image: nginx:1.27
    ports:
        - 0.0.0.0:80:80
        - 0.0.0.0:443:443
    volumes:
        - /home/_Dockers/nginx/conf.d:/etc/nginx/conf.d:ro
        - /home/_Dockers/nginx/include.d:/etc/nginx/include.d:ro
        - /home/_Dockers/nginx/ssl.d:/etc/nginx/ssl.d:ro
        - /home/_Dockers/nginx/static:/var/www:ro
        - /home/_Dockers/nginx/cache:/var/cache/nginx/proxy_temp:rw
        - /home/_Dockers/letsencrypt/etc+letsencrypt:/etc/letsencrypt:ro
    restart: always
    logging:
      driver: syslog
      options:
        syslog-address: udp://127.0.0.1:514
        syslog-facility: local0
        tag: nginx
    extra_hosts:
        - upstreams:172.17.0.1

